### ISSUE TITLE
Algorithm fails while computing route

### ISSUE THREAD

**Issue by LucaOdetti** [enricofer/wind_forecast_routing#15]
Log:

Versione di QGIS: 3.16.6-Hannover
Revisione codice QGIS: bfd36fddc9
Versione di Qt: 5.11.2
Versione di GDAL: 3.1.4
Versione di GEOS: 3.8.1-CAPI-1.13.3
Versione di PROJ: Rel. 6.3.2, May 1st, 2020
Algoritmo in esecuzione...
In avvio l'algoritmo 'windrouting' …
Parametri in ingresso:
{ 'END_POINT' : '8.359257,40.140330 [EPSG:4326]', 'GRIB' : 'C:/Users/107775/Downloads/20210520_145802_ICON_EU_P06_.grb2', 'OUTPUT_ROUTE' : 'TEMPORARY_OUTPUT', 'OUTPUT_WAYPOINTS' : 'TEMPORARY_OUTPUT', 'POLAR' : 79, 'START_POINT' : '8.630326,40.958293 [EPSG:4326]', 'START_TIME' : QDateTime(QDate(2021, 5, 20), QTime(18, 41, 41)), 'WIND_DATASET_INDEX' : 0 }

step 2: 2021-05-20 19:41:41.443000
step 3: 2021-05-20 20:41:41.443000
step 4: 2021-05-20 21:41:41.443000
step 5: 2021-05-20 22:41:41.443000
step 6: 2021-05-20 23:41:41.443000
step 7: 2021-05-21 00:41:41.443000
step 8: 2021-05-21 01:41:41.443000
step 9: 2021-05-21 02:41:41.443000
step 10: 2021-05-21 03:41:41.443000
step 11: 2021-05-21 04:41:41.443000
step 12: 2021-05-21 05:41:41.443000
step 13: 2021-05-21 06:41:41.443000
step 14: 2021-05-21 07:41:41.443000
step 15: 2021-05-21 08:41:41.443000
step 16: 2021-05-21 09:41:41.443000
step 17: 2021-05-21 10:41:41.443000
step 18: 2021-05-21 11:41:41.443000
step 19: 2021-05-21 12:41:41.443000
step 20: 2021-05-21 13:41:41.443000
step 21: 2021-05-21 14:41:41.443000
step 22: 2021-05-21 15:41:41.443000
step 23: 2021-05-21 16:41:41.443000
step 24: 2021-05-21 17:41:41.443000
step 25: 2021-05-21 18:41:41.443000
step 26: 2021-05-21 19:41:41.443000
step 27: 2021-05-21 20:41:41.443000
step 28: 2021-05-21 21:41:41.443000
step 29: 2021-05-21 22:41:41.443000
step 30: 2021-05-21 23:41:41.443000
step 31: 2021-05-22 00:41:41.443000
step 32: 2021-05-22 01:41:41.443000
step 33: 2021-05-22 02:41:41.443000
step 34: 2021-05-22 03:41:41.443000
step 35: 2021-05-22 04:41:41.443000
step 36: 2021-05-22 05:41:41.443000
step 37: 2021-05-22 06:41:41.443000
step 38: 2021-05-22 07:41:41.443000
step 39: 2021-05-22 08:41:41.443000
step 40: 2021-05-22 09:41:41.443000
step 41: 2021-05-22 10:41:41.443000
step 42: 2021-05-22 11:41:41.443000
step 43: 2021-05-22 12:41:41.443000
step 44: 2021-05-22 13:41:41.443000
step 45: 2021-05-22 14:41:41.443000
step 46: 2021-05-22 15:41:41.443000
step 47: 2021-05-22 16:41:41.443000
step 48: 2021-05-22 17:41:41.443000
step 49: 2021-05-22 18:41:41.443000
step 50: 2021-05-22 19:41:41.443000
step 51: 2021-05-22 20:41:41.443000
step 52: 2021-05-22 21:41:41.443000
step 53: 2021-05-22 22:41:41.443000
step 54: 2021-05-22 23:41:41.443000
step 55: 2021-05-23 00:41:41.443000
step 56: 2021-05-23 01:41:41.443000
step 57: 2021-05-23 02:41:41.443000
step 58: 2021-05-23 03:41:41.443000
step 59: 2021-05-23 04:41:41.443000
step 60: 2021-05-23 05:41:41.443000
step 61: 2021-05-23 06:41:41.443000
step 62: 2021-05-23 07:41:41.443000
step 63: 2021-05-23 08:41:41.443000
step 64: 2021-05-23 09:41:41.443000
step 65: 2021-05-23 10:41:41.443000
step 66: 2021-05-23 11:41:41.443000
step 67: 2021-05-23 12:41:41.443000
step 68: 2021-05-23 13:41:41.443000
step 69: 2021-05-23 14:41:41.443000
step 70: 2021-05-23 15:41:41.443000
step 71: 2021-05-23 16:41:41.443000
step 72: 2021-05-23 17:41:41.443000
step 73: 2021-05-23 18:41:41.443000
step 74: 2021-05-23 19:41:41.443000
step 75: 2021-05-23 20:41:41.443000
step 76: 2021-05-23 21:41:41.443000
step 77: 2021-05-23 22:41:41.443000
step 78: 2021-05-23 23:41:41.443000
step 79: 2021-05-24 00:41:41.443000
step 80: 2021-05-24 01:41:41.443000
step 81: 2021-05-24 02:41:41.443000
step 82: 2021-05-24 03:41:41.443000
step 83: 2021-05-24 04:41:41.443000
step 84: 2021-05-24 05:41:41.443000
Traceback (most recent call last):
File "C:/Users/107775/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wind_forecast_routing-master\wind_forecast_routing_algorithm.py", line 259, in processAlgorithm
res = route_process.step()
File "C:\Users\107775\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\wind_forecast_routing-master\extlibs\weatherrouting\routing.py", line 90, in step
res = self.algorithm.route (self.log[-1], self.time, self.position, nextwp)
File "C:\Users\107775\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\wind_forecast_routing-master\extlibs\weatherrouting\routers\linearbestisorouter.py", line 71, in route
generate_path(minP)
UnboundLocalError: local variable 'minP' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:/Users/107775/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wind_forecast_routing-master\wind_forecast_routing_algorithm.py", line 267, in processAlgorithm
feedback.pushInfo("Error: %s" % e.message)
AttributeError: 'UnboundLocalError' object has no attribute 'message'

Esecuzione fallita dopo 98.21 secondi

Caricamento layer
Algoritmo 'windrouting' terminato

**Comment by LucaOdetti** [comment]
Ed ecco il GRIB

[20210520_145802_ICON_EU_P06_.zip](https://github.com/enricofer/wind_forecast_routing/files/6518295/20210520_145802_ICON_EU_P06_.zip)

**Comment by enricofer** [comment]
Looking into the grib, It seems that between 2021-05-20 h 23:00 and 2021-05-21 h 04:00 around E8.20° N40.40° there is a very low wind condition that confuse the routing algorithm. Maybe this cause a long/infinite loop condition that bring the analysis outside the grib scope.

**Comment by enricofer** [comment]
This is due to track path shortness. fixed by https://github.com/enricofer/wind_forecast_routing/commit/bea90d2d0e203359b20a1f90605db97ea0089e7c
