### ISSUE TITLE
External libraries

### ISSUE THREAD

**Issue by dakk** [enricofer/wind_forecast_routing#2]
It might make more sense to develop both in the same repository (libgweatherrouting) while add the reference in the requirements.txt of this plugin. Same thought  for LatLon23.

**Comment by enricofer** [comment]
Hi Davide, unfortunately QGIS plugin support for external modules is very limited. Maybe in the next releases will be a virtualenv per user profile (https://github.com/qgis/QGIS-Enhancement-Proposals/issues/202) but for now we have to put the required modules in a separate directory and pointing the environment variables to make them discoverable by python subsystem.
Anyway the plugin in its actual form is only a rough way to display libweatherrouting results in a friendly environment, for verifying with @pcav the routing efficiency and issues and eventually propose improvements and also understand the functioning in the deep

**Comment by dakk** [comment]
@enricofer got it! Anyway if qgis plugin aren't allowed to install python deps, an almost-ideal solution for the future is to use git submodules feature
