### ISSUE TITLE
Better wind colour scale

### ISSUE THREAD

**Issue by pcav** [enricofer/wind_forecast_routing#23]
It would be good for readability to add a standard scale for wind strength, with absolute values. This is a good example: https://community.windy.com/topic/7233/wind-colors-for-sailors-and-for-everyone
I'm available for help.

**Comment by enricofer** [comment]
There is an issue on symbology loading on mesh layer.
Here is a branch https://github.com/enricofer/wind_forecast_routing/tree/windy_color_ramp where is defined windy color ramp:
https://github.com/enricofer/wind_forecast_routing/blob/windy_color_ramp/grib.qml
that is applied to downloaded grib layer without success: https://github.com/enricofer/wind_forecast_routing/blob/9924c55d98bb6e2ea03d6a2fc17be43d76c84dc7/wind_forecast_routing.py#L251

**Comment by pcav** [comment]
I see, thanks!

**Comment by enricofer** [comment]
[fix temporal ranges reset issue loading new grib style](https://github.com/enricofer/wind_forecast_routing/commit/ae43929a88cdc6d8c0b553d82b4ef9dcc9c3336b) solved  keeping default temporal properties and reloading them after loading grib layer alternate style
