### ISSUE TITLE
Better placement for the bounding box layer

### ISSUE THREAD

**Issue by pcav** [enricofer/wind_forecast_routing#24]
Currently the bouding box layer (Estratto in IT) is placed above the current layer. It would be more appropriate to add it to the "Wind routing..." group, and perhaps deactivate it by default (useful for debugging, not so much for normal use).

**Comment by enricofer** [comment]
Removed. It is redundant as It's already loaded as "context" 
fix: https://github.com/enricofer/wind_forecast_routing/commit/52ece0ca9fd98421891b2b36878a04f47a9d1916
