### ISSUE TITLE
Start time animation at the end of the run?

### ISSUE THREAD

**Issue by pcav** [enricofer/wind_forecast_routing#25]
After autloading of the results, it would be good to automatically start the animation to see the results in time.

**Comment by enricofer** [comment]
Temporal controller time range is now automatically configured.
Animation can be performed after the algorithm run checking the new parameter  "Animate route with temporal controller at the end of algorithm processing" in algorithm launch dialog.
fix: https://github.com/enricofer/wind_forecast_routing/commit/c14931c5ce56b344a74b84ce81a79289a0f012ff
