### ISSUE TITLE
Move start and endpoint outside land masses

### ISSUE THREAD

**Issue by pcav** [enricofer/wind_forecast_routing#3]
If the user places start or end points inland, either by mistake or because of too rough coastline layer, the alg fails, with an ambiguous error message.
It would be good before running the analysis to move the points at sea, to the closest point along the coastline (better if taking into account boat draft).

**Comment by pcav** [comment]
A warning should also be issued to the user.

**Comment by enricofer** [comment]
included in some new checks: https://github.com/enricofer/wind_forecast_routing/commit/b09464eb19115d3c2f8ea2a80a4244655ff76552
