### ISSUE TITLE
Check grib projection

### ISSUE THREAD

**Issue by pcav** [enricofer/wind_forecast_routing#6]
I believe gribs should be EPSG:4326 (am I wrong?). Often, dowloaded files do not have an explicit EPSG set, or have a wrong one.
It would be good etiher:
* warn the user about missing or wrong EPSG
* assign EPSG:4326 by default

**Comment by enricofer** [comment]
https://github.com/enricofer/wind_forecast_routing/commit/31efc7736213effb1c56ec3668732c934f0971ff

**Comment by enricofer** [comment]
Assigning EPSG:4326 to meshlayer seems suffits
