### ISSUE TITLE
Last leg artifact?

### ISSUE THREAD

**Issue by pcav** [enricofer/wind_forecast_routing#9]
The last leg of the routing seems consistently wrong, turning N for no apparent reason, see attached image.
Probably a bug in the underlying lib?
![circeo-n](https://user-images.githubusercontent.com/691842/118374205-1d4c8d00-b5bb-11eb-8ff6-01d0bdbc8bb3.png)

**Comment by pcav** [comment]
Fixed, thanks @enricofer 
![circeo-n](https://user-images.githubusercontent.com/691842/118387440-df815000-b61e-11eb-8c74-7b2b5b5ab8b3.png)

**Comment by enricofer** [comment]
fixed with https://github.com/enricofer/wind_forecast_routing/commit/722c86ea8fb93811b671433aeab5c4356d7d6113
